//
// Copyright (c) 2014 Max Vilimpoc. All rights reserved.
//
// We need a variable to track page loads in progress and ignore onBeforeNavigate
// events that are generated by the same process ID + tab ID once a navigation
// has begun.
//
// Here's some data.
//
// onBeforeNavigate{"frameId":0,"parentFrameId":-1,"processId":539,"tabId":440,"timeStamp":1398929951106.273,"url":"https://www.google.co.uk/_/chrome/newtab?espv=210&ie=UTF-8"} background.js:8
// onBeforeNavigate{"frameId":0,"parentFrameId":-1,"processId":540,"tabId":440,"timeStamp":1398929952411.135,"url":"http://www.nytimes.com/"} background.js:8
// onBeforeNavigate{"frameId":2,"parentFrameId":0,"processId":540,"tabId":440,"timeStamp":1398929953250.223,"url":"http://www.nytimes.com/packages/html/recommendations/ad.html"} background.js:8
// onBeforeNavigate{"frameId":3,"parentFrameId":0,"processId":540,"tabId":440,"timeStamp":1398929953252.064,"url":"http://srv.dynamicyield.com/st?sec=8765344&id=May%201%202014"} background.js:8
// onBeforeNavigate{"frameId":4,"parentFrameId":0,"processId":540,"tabId":440,"timeStamp":1398929956192.813,"url":"about:blank"} background.js:8
// onBeforeNavigate{"frameId":5,"parentFrameId":0,"processId":540,"tabId":440,"timeStamp":1398929956883.432,"url":"http://ads.dynamicyield.com/abadimage/my-ad.html"} background.js:8
//
// onCompleted{"frameId":0,"processId":539,"tabId":440,"timeStamp":1398929951662.93,"url":"https://www.google.co.uk/_/chrome/newtab?espv=210&ie=UTF-8"} background.js:12
// onCompleted{"frameId":2,"processId":540,"tabId":440,"timeStamp":1398929954916.399,"url":"http://www.nytimes.com/packages/html/recommendations/ad.html"} background.js:12
// onCompleted{"frameId":3,"processId":540,"tabId":440,"timeStamp":1398929956100.84,"url":"http://srv.dynamicyield.com/st?sec=8765344&id=May%201%202014"} background.js:12
// onCompleted{"frameId":4,"processId":540,"tabId":440,"timeStamp":1398929956193.462,"url":"about:blank"} background.js:12
// onCompleted{"frameId":4,"processId":540,"tabId":440,"timeStamp":1398929956193.634,"url":"about:blank"} background.js:12
// onCompleted{"frameId":5,"processId":540,"tabId":440,"timeStamp":1398929957044.0012,"url":"http://ads.dynamicyield.com/abadimage/my-ad.html"} background.js:12
// onCompleted{"frameId":0,"processId":540,"tabId":440,"timeStamp":1398929957047.105,"url":"http://www.nytimes.com/"}
//
// onBeforeNavigate{"frameId":0,"parentFrameId":-1,"processId":545,"tabId":442,"timeStamp":1398930514966.6719,"url":"https://www.google.co.uk/_/chrome/newtab?espv=210&ie=UTF-8"} background.js:8
// onCompleted{"frameId":0,"processId":545,"tabId":442,"timeStamp":1398930515566.092,"url":"https://www.google.co.uk/_/chrome/newtab?espv=210&ie=UTF-8"} background.js:12
// onBeforeNavigate{"frameId":0,"parentFrameId":-1,"processId":545,"tabId":442,"timeStamp":1398930532087.2158,"url":"https://www.google.co.uk/_/chrome/newtab?espv=210&ie=UTF-8"} background.js:8
// onCompleted{"frameId":0,"processId":545,"tabId":442,"timeStamp":1398930532597.548,"url":"https://www.google.co.uk/_/chrome/newtab?espv=210&ie=UTF-8"} background.js:12
// onBeforeNavigate{"frameId":0,"parentFrameId":-1,"processId":546,"tabId":442,"timeStamp":1398930548675.8088,"url":"http://vilimpoc.org/"} background.js:8
// onCompleted{"frameId":0,"processId":546,"tabId":442,"timeStamp":1398930549596.515,"url":"https://vilimpoc.org/"} background.js:12
//
// onBeforeNavigate{"frameId":12,"parentFrameId":0,"processId":235,"tabId":152,"timeStamp":1399393519299.13,"url":"about:blank"} background.js:121
// onCommitted{"frameId":12,"processId":235,"tabId":152,"timeStamp":1399393519306.4329,"transitionQualifiers":[],"transitionType":"auto_subframe","url":"about:blank"} background.js:127
// onCompleted{"frameId":12,"processId":235,"tabId":152,"timeStamp":1399393519307.112,"url":"about:blank"}
//
// So to track a new page load, we need to watch for:
//
//     onBeforeNavigate with -- (0 == frameId && -1 == parentFrameId) -- save the tabId and URL, because this is a new page load.
//     onCompleted      with -- (0 == frameId)                        -- remove the tabId and URL from tracking, because this page load is done.
//
// onChanged{"cause":"explicit","cookie":{"domain":".nytimes.com","expirationDate":1430480382.545723,"hostOnly":false,"httpOnly":false,"name":"nyt-a","path":"/","secure":false,"session":false,"storeId":"0","value":"f61f999b26a346a24c6344bcd9d1e3e0"},"removed":false}
//

"use strict";
Logger.useDefaults();

/**
 * Defined just for WebStorm to not keep asking.
 */
var chrome = chrome || {};

/**
 * Tracking table for in-flight page loads.
 *
 * key -- "tabId-processId-frameId"
 */
var inFlight = {};

/**
 * A list of all page loads made during a session.
 *
 * Objects within the list have the following properties for filtering:
 *
 * topFrame -- true or false depending on whether the load was of a top-level frame or a subframe.
 *
 * @type {Array}
 */
var allPageLoads = [];

/**
 * Use the event count to group the page-load actions together.
 *
 * In other words, even if a page load action is
 * occurring due to a client_redirect / META refresh
 * we need a way to say that all the actions between
 * the onCommitted and onComplete/ErrorOccurred
 * belong to one page load action.
 *
 * Example: nytimes.com website will META refresh
 * every N seconds, so we want to make sure that
 * all the actions are associated with a page load
 * ID.
 *
 * @type {number}
 */
var pageLoadCount = 0;

/**
 *
 * @type {Array}
 */
var cookieEvents = [];


var makeKey = function(tabId, processId, frameId) {
    return tabId + "-" + processId + "-" + frameId;
};

var stampStart = function(details) {
    // Immediate check and return.
    if ('about:blank' === details.url) return;

    // TODO: Immediate check and return.
    // if (tab is incognito) return;

    var key      = makeKey(details.tabId, details.processId, details.frameId);  //!< All frames and subframes have a unique identifier.
    var hostname = new URL(details.url).hostname;
    var topFrame = false;
    var process  = makeKey(details.tabId, details.processId, 0);
    var pageload = -1;                                                          //!< All actions between the start and finish of the top-frame action count as the same event.

    var stamp;

    // We need to mark the navigation as user-started when it is using frameId 0.
    //
    // This also means it is /not/ a subframe.
    //
    // If it IS a subframe, then we should add it to the list of subStamps being
    // tracked by the top frame.
    if (0 == details.frameId) {
        topFrame = true;
        pageload = pageLoadCount++;
    } else {
        // Look for the parent-frame timestamp object, and add a reference to the
        // .subStamps property.
        //
        // The parent-frame reference should remain valid in the in-flight table
        // until all subframes have loaded anyway.
        topFrame = false;

        // Look up the parent-frame timestamp and make sure that this subframe
        // is associated with the same eventId.
        if (process in inFlight) {
            stamp    = inFlight[process];
            pageload = stamp.eventId;
        } else {
            // If a subframe load occurs after the parent-frame is no longer in-flight,
            // then it needs its own separate event count.
            pageload = pageLoadCount++;
        }

    }

    // Create an in-flight timestamp object, which waits for the frame to finish loading.
    inFlight[key] = {
        type: 'timestamp',
        tabId: details.tabId,
        process: process,
        pageload: pageload,
        start: new Date().getTime(),
        finish: 0,
        topFrame: topFrame,
        hostname: hostname,
        url: details.url,
        subStamps: [] };

    console.log('key: ' + key + " = " + JSON.stringify(inFlight[key]));
};

var stampFinish = function(details) {
    // Immediate check and return.
    if ('about:blank' === details.url) return;

    // TODO: Immediate check and return.
    // if (tab is incognito) return;

    var key = makeKey(details.tabId, details.processId, details.frameId);
    var stamp;

    var storeStamp = {};

    // Get the timestamp from the in-flight table, and set the finished-loading timestamp.
    if (key in inFlight) {
        stamp = inFlight[key];
        stamp.finish = new Date().getTime();

        // Save the page-load record to a more permanent log.
        allPageLoads.push(stamp);

        // Persist the record to LocalStorage, using a timestamp as the key (irrelevant).
        storeStamp[new Date().getTime()] = stamp;
        chrome.storage.local.set(storeStamp, function() {
            console.log("Saved timestamp data.");
            if (chrome.runtime.lastError) console.log(chrome.runtime.lastError);
        });

        // Remove the page-load record from the in-flight table.
        delete inFlight[key];
    }

    console.log('key: ' + key + " = " + JSON.stringify(stamp));
};


/****************************************************************************
 * webNavigation event handlers.
 ****************************************************************************/


// var onBeforeNavigateListener = function(details) {
//     console.log("onBeforeNavigate" + JSON.stringify(details));
//
//     stampStart(details);
// };

var onCommitted = function(details) {
    console.log("onCommitted" + JSON.stringify(details));

    stampStart(details);
};

var onCompletedListener = function(details) {
    console.log("onCompleted" + JSON.stringify(details));

    stampFinish(details);
};

var onErrorOccurred = function(details) {
    console.log("onErrorOccurred" + JSON.stringify(details));

    stampFinish(details);
};

// chrome.webNavigation.onBeforeNavigate.addListener(onBeforeNavigateListener);
chrome.webNavigation.onCommitted.addListener(onCommitted);
chrome.webNavigation.onCompleted.addListener(onCompletedListener);
chrome.webNavigation.onErrorOccurred.addListener(onErrorOccurred);


/****************************************************************************
 * webRequest event handlers.
 ****************************************************************************/


var standardFilter = {
    urls: ['http://*/*', 'https://*/*']
};

chrome.webRequest.onBeforeSendHeaders.addListener(function(details) {
    console.log("onBeforeSendHeaders" + JSON.stringify(details));
}, standardFilter, ['requestHeaders']);

chrome.webRequest.onSendHeaders.addListener(function(details) {
    console.log("onSendHeaders" + JSON.stringify(details));
}, standardFilter, ['requestHeaders']);

chrome.webRequest.onHeadersReceived.addListener(function(details) {
    console.log("onHeadersReceived" + JSON.stringify(details));
}, standardFilter, ['responseHeaders']);

chrome.webRequest.onCompleted.addListener(function(details) {
    console.log("onCompleted" + JSON.stringify(details));
}, standardFilter, ['responseHeaders']);


/****************************************************************************
 * Cookie event handlers.
 ****************************************************************************/


chrome.cookies.onChanged.addListener(function(details) {
    // Add a timestamp to the Details object (as it's not currently provided).
    details['timestamp'] = new Date().getTime();
    console.log("onChanged" + JSON.stringify(details));
});












/****************************************************************************
 * Management page stuff.
 ****************************************************************************/

function focusOrCreateTab(url) {
  chrome.windows.getAll({"populate":true}, function(windows) {
    var existing_tab = null;
    for (var i in windows) {
      var tabs = windows[i].tabs;
      for (var j in tabs) {
        var tab = tabs[j];
        if (tab.url == url) {
          existing_tab = tab;
          break;
        }
      }
    }
    if (existing_tab) {
      chrome.tabs.update(existing_tab.id, {"selected":true});
    } else {
      chrome.tabs.create({"url":url, "selected":true});
    }
  });
}

chrome.browserAction.onClicked.addListener(function(tab) {
  var manager_url = chrome.extension.getURL("manager.html");
  focusOrCreateTab(manager_url);
});
